version: '2.1'

services:
  b1:
    build: ./bgp/.
    volumes:
      - ./volumes/bgp/b1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b1/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: bgp:20180426
    container_name: router_b1
    privileged: true
    ports:
      #admin
      - 10101:2601
      #ospf ipv6
      - 10103:2606
      #bgp
      - 10104:2605
    networks:
      nb1r3:
        ipv6_address: 2001:13::10
      nb1r5:
        ipv6_address: 2001:15::10
      nb1r7:
        ipv6_address: 2001:17::10
      nb1b2:
        ipv6_address: 2001:b12::10 
 
  r3:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    container_name: router_r3
    privileged: true
    ports:
      #admin
      - 10311:2601
      #ospf ipv6
      - 10313:2606
    networks:
      nb1r3:
        ipv6_address: 2001:13::30
      nr3:
        ipv6_address: 2001:33::31
          
  r5:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r5/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r5/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    container_name: router_r5
    privileged: true
    ports:
      #admin
      - 10511:2601
      #ospf ipv6
      - 10513:2606
    networks:
      nb1r5:
        ipv6_address: 2001:15::50
      nr5r7:
        ipv6_address: 2001:57::50
      nr5h11:
        ipv6_address: 2001:5c::50

  r7:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r7/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r7/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    container_name: router_r7
    privileged: true
    ports:
      #admin
      - 10711:2601
      #ospf ipv6
      - 10713:2606
    networks:
      nb1r7:
        ipv6_address: 2001:17::70
      nr5r7:
        ipv6_address: 2001:57::70
      nr7h13:
        ipv6_address: 2001:7c::70

  h11: #configuracion host 11
    build: ./host/.
    volumes: #mapeo de directorios "host:contenedor"
      - ./volumes/scripts/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./volumes/scripts/h11/borrar_dgw.sh:/script/borrar_dgw.sh:ro
    image: host:20180400 #imagen de docker a usar
    container_name: host_h11
    privileged: true
    networks:
      nr5h11: #direccion para la interfaz eth0 conectada a r5
        ipv6_address: 2001:5c::11

  h13: #configuracion host 13
    build: ./host/.
    volumes: #mapeo de directorios "host:contenedor"
      - ./volumes/scripts/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./volumes/scripts/h13/borrar_dgw.sh:/script/borrar_dgw.sh:ro
    image: host:20180400 #imagen de docker a usar
    container_name: host_h13
    privileged: true
    networks:
      nr7h13: #direccion para la interfaz eth0 conectada a r7
        ipv6_address: 2001:7c::13


networks:
  nb1r3:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:13::/64
  nb1r5:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:15::/64
  nb1r7:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:17::/64
  nb1b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:b12::/64
  nr3:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:33::/64
  nr5r7:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:57::/64
  nr5h11:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:5c::/64
  nr7h13:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:7c::/64
 
