version: '2.1'

services:

  web:
   image: nginx
   container_name: nginx
   volumes:
    - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./volumes/nginx/ssl:/etc/nginx/ssl
   ports:
    - "8080:80"
   environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
   networks:
     nrSTRAPINGINX:
       ipv6_address: 2001:bbbb:4445::10 
     nrR4NGINX:
       # NGINX con router r4
       ipv6_address: 2001:bbbb:4443::20

##para entrar por navegador por container nginx a strappi (no borrar default gateways)
#http://[2001:bbbb:4445::10]:80
##para entrar por navegador pero por el router 4 a strappi
#http://[2001:bbbb:4443::20]:80   
##para entrar por cualquier container por NGINX
#docker exec -ti router_r4 curl get http://[2001:bbbb:4443::20]:80
#docker exec -ti router_r6 curl get http://[2001:bbbb:4443::20]:80
## tambien se usa el GET desde el navegador unicamente
#GET http://[2001:bbbb:4443::20]:80

##hago el ejemplo del strapi "quick start"
##desde el container para ver lo que se ingresa uso
#docker exec -ti router_r6 curl get http://[2001:bbbb:4443::20]:80/product

  api:
##    build: ./strapi/.
    image: strapi/strapi
    container_name: strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=2001:bbbb:4445::20
    ports:
      - 1337:1337
    volumes:
      - ./volumes/strapi-app:/usr/src/api/strapi-app
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - db
    restart: always
    networks:
      nrSTRAPINGINX:
        ipv6_address: 2001:bbbb:4445::20

  db:
    image: mongo
    container_name: mongoDB
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./volumes/db:/data/db
    restart: always
    networks:
      nrSTRAPINGINX:
        ipv6_address: 2001:bbbb:4445::30

  b2:
    build: ./bgp/.
    container_name: router_bgp2
    volumes:
      - ./volumes/bgp/b2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b2/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: bgp:20180426
    privileged: true
    ports:
      #admin
      - 10201:2601
      #ospf ipv6
      - 10203:2606
      #bgp
      - 10204:2605
    networks:
      rb1b2:
        ipv6_address: 2001:b1b2::6
      nr4b2:
        ipv6_address: 2001:bbbb:2224::6
      nr6b2:
        ipv6_address: 2001:bbbb:2226::6
      nr8b2:
        ipv6_address: 2001:bbbb:2228::6

  r4:
    build: ./ospf/.
    container_name: router_r4
    volumes:
      - ./volumes/ospf/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10441:2601
      #ospf ipv6
      - 10443:2606
    networks:
      nr4b2:
        ipv6_address: 2001:bbbb:2224::10
      nrR4NGINX:
        ipv6_address: 2001:bbbb:4443::10
      nr4:
        ipv6_address: 2001:bbbb:4444::10
  r6:
    build: ./ospf/.
    container_name: router_r6
    volumes:
      - ./volumes/ospf/r6/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r6/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10661:2601
      #ospf ipv6
      - 10663:2606
    networks:
      nr6b2:
        ipv6_address: 2001:bbbb:2226::10
      nr6:
        ipv6_address: 2001:bbbb:6666::10
      nr68:
        ipv6_address: 2001:bbbb:6688::10
      

  r8:
    build: ./ospf/.
    container_name: router_r8
    volumes:
      - ./volumes/ospf/r8/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r8/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10881:2601
      #ospf ipv6
      - 10883:2606
    networks:
      nr8b2:
        ipv6_address: 2001:bbbb:2228::10
      nr8:
        ipv6_address: 2001:bbbb:8888::10
      nr68:
        ipv6_address: 2001:bbbb:6688::20

  
  h12:
    build: ./hosts/.
    container_name: host_h12
    volumes:
      - ./volumes/hosts/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./volumes/nginx/ssl:/usr/share/ca-certificates
      - ./volumes/hosts/h12/borrar_dfg.sh:/script/borrar_dfg.sh:ro
    privileged: true
    tty: true
    ports:
      #admin
      - 10112:2601
    networks:
      nr6:
        ipv6_address: 2001:bbbb:6666::20

  h14:
    build: ./hosts/.
    container_name: host_h14
    volumes:
      - ./volumes/hosts/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./volumes/nginx/ssl:/usr/share/ca-certificates
      - ./volumes/hosts/h14/borrar_dfg.sh:/script/borrar_dfg.sh:ro
    privileged: true
    tty: true
    ports:
      #admin
      - 10114:2601
    networks:
      nr8:
        ipv6_address: 2001:bbbb:8888::20

  bind:
    build: ./dns/.
    environment:
      - ROOT_PASSWORD=ubuntu
    container_name: DNS_service
    volumes:
       - ./volumes/webmin_datos:/data:rw
    networks:
      nr4:
        ipv6_address: 2001:bbbb:4444::20
          
networks:
  rb1b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:b1b2::/64
  nr4b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:2224::/64
  nr6b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:2226::/64
  nr8b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:2228::/64
  nr4:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:4444::/64
  
  nr6:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:6666::/64
  nr8:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:8888::/64
 
  nr68:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:6688::/64
  
  nrSTRAPINGINX:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:4445::/64
  nrR4NGINX:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:4443::/64
